on: [ push, pull_request ]

name: Publish events JSON
jobs:
  validate-toml:
    uses: ./.github/workflows/toml-validate.yml

  publish-json:
    needs: [validate-toml]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: NPM Install
        run: |
          cd website && npm install

      - name: Create events JSON
        run: |
          cd website
          node -e "import('./lib/data.js').then(async ({loadEvents}) => { const events = await loadEvents(); console.log(JSON.stringify(events, null, 2)); })" > ${{ github.workspace }}/events-${{ github.sha }}.json

      - name: Attach JSON artifact
        uses: actions/upload-artifact@v2
        with:
          name: events-${{ github.sha }}.json
          path: ${{ github.workspace }}/events-${{ github.sha }}.json
          if-no-files-found: error
